---
trigger: none

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
  displayName: 'Set Python Version'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    python fetch_jira_ticket.py %TICKET_ID%
  displayName: 'Fetch Jira Ticket Details'
  env:
    JIRA_DOMAIN: $(JIRA_DOMAIN)
    JIRA_EMAIL: $(JIRA_EMAIL)
    JIRA_API_TOKEN: $(JIRA_API_TOKEN)
